# application.yml — главный конфигурационный файл Spring Boot.

server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: Bank_REST
  
  # Конфигурация базы данных
  datasource:
    url: jdbc:postgresql://localhost:5433/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  # Конфигурация JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        batch_versioned_data: true
  
  # Конфигурация Liquibase
  liquibase:
    enabled: true
    change-log: classpath:db/migration/changelog.yaml
    contexts: dev
  
  # Конфигурация валидации
  validation:
    enabled: true

# Конфигурация безопасности
# security:
#   jwt:
#     secret: 
#     expiration: 86400000 # 24 часа в миллисекундах

# Конфигурация логирования
logging:
  level:
    root: INFO
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  
  file:
    name: logs/bank-app.log
    max-size: 10MB
    max-history: 30

# Конфигурация Swagger/OpenAPI
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

# Конфигурация приложения
app:
  # Настройки для номеров карт
  card:
    number-length: 16
    expiry-years: 4
  
  # Настройки пагинации
  pagination:
    default-page-size: 20
    max-page-size: 100
  
  # Настройки безопасности
  security:
    password:
      min-length: 6
      require-special-chars: false
    session:
      timeout: 3600 # 1 час в секундах

# Профили
---
spring:
  config:
    activate:
      on-profile: dev
  
  datasource:
    url: jdbc:postgresql://localhost:5433/bankdb
    username: bankuser
    password: bankpass
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/bankdb}
    username: ${DB_USERNAME:bankuser}
    password: ${DB_PASSWORD:bankpass}
  
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  
  liquibase:
    contexts: prod

logging:
  level:
    root: WARN
    com.example.bankcards: INFO
# Переменные окружения для production
app:
  security:
    jwt:
      secret: ${JWT_SECRET:your-production-secret-key}

